version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/tecno-backend
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: ubuntu

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 120
      runas: ubuntu

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ubuntu
